### ISSUE TITLE
Not able to change configuration of the integration

### ISSUE THREAD

**Issue by canedje** [xirixiz/homeassistant-afvalwijzer#328] opened 2024-12-06 16:48 UTC
### The problem

I installed the integration after update of afvalwijzer 2024.12.1.
My provider is mijnafvalwijzer
I I do want to change the configuration it is not possible.
The configuration keeps as it was
![image](https://github.com/user-attachments/assets/620764b7-736d-42d9-86a1-e7cdbf6d5b1f)

### Version of afvalwijzer integration having the issue?

afvalwijzer - 2024.12.1

### Version of Home Assistant Core having the issue?

core - 2024.12.0

### Anything in the logs that might be useful for us?

```txt
no errors
```

**Comment by RobertZwets** [comment] 2024-12-06 19:25
manualy deleted all  sensor sensor items, deleted the app, re installed is and now it works again

**Comment by canedje** [comment] 2024-12-07 07:58
I tried also, but not working for me

**Comment by vincentkoevoets** [comment] 2024-12-09 14:06
I missed the release note saying that you have to delete your current configuration of Afvalwijzer, and re-add it via Add integration flow. Info is here https://github.com/xirixiz/homeassistant-afvalwijzer/releases/tag/2024.12.01. Maybe you have missed it too?
Working for me again now.

**Comment by canedje** [comment] 2024-12-09 14:34
> I missed the release note saying that you have to delete your current configuration of Afvalwijzer, and re-add it via Add integration flow. Info is here https://github.com/xirixiz/homeassistant-afvalwijzer/releases/tag/2024.12.01. Maybe you have missed it too? Working for me again now.

No. The integration itself is working fine. 
I removed the old sensor and added the settings by the configuration itself
Except I can not change the configuration settings as shown in the picture above

**Comment by vincentkoevoets** [comment] 2024-12-09 14:37
I mean you need to delete the previous configuration, not the sensors. Is suppose when there is an old configuration file or code in HA configuration.yaml, things get tripped up. If that is all in order, I'm afraid I don't know what the problem is.

**Comment by canedje** [comment] 2024-12-09 15:00
I did remove all before installing the new integration

**Comment by vincentkoevoets** [comment] 2024-12-10 18:40
I should have done this before, but I tested it today. Indeed I can also not change the configuration of the integration. I can change all the value, but when I click Submit, things do not get saved. 
So that's a +1 from me.

**Comment by xirixiz** [comment] 2024-12-17 13:36
Hi, this is odd. Somehow I missed all open issues. I just got a new laptop and suddenly a lot of open issues are visible. I`ll have a look and come back to it asap. Thanks!

**Comment by xirixiz** [comment] 2024-12-18 08:46
Fixed in the upcoming release (end of this week)

**Closed by xirixiz** 2024-12-18 08:46 UTC
Labels: bug
